dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - yarn.lock
          - package.json
github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
lint:
  - changed-files:
      - any-glob-to-any-file:
          - .tslint.json
