name: 'Auto-label merge conflicts'
description: 'Github Action to automatically label PRs with "conflict" label'
author: 'Marko Schilde'
branding:
  icon: 'alert-octagon'
  color: 'gray-dark'
inputs:
  CONFLICT_LABEL_NAME:
    description: 'label name used to marked PRs with merge conflicts'
    required: true
  GITHUB_TOKEN:
    description: 'Github token / secret'
    required: true
  COMMENT:
    description: 'Text to be commented on the PR. If not set, nothing will be commented.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.CONFLICT_LABEL_NAME }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.COMMENT }}
